메인페이지 msw 연결
Step3-kakao-tech-campus/Team13_FE pull request #117
Opened 2023-11-05 16:38 UTC by Klomachenko

## 주요 사항
- PR의 주요 사항을 작성

## 스크린샷
구현물 스크린샷 첨부

## 궁금한 점
코드 리뷰 요청할 시 중점적으로 보길 바라는 점 혹은 궁금한 점

### 관련 이슈
이슈를 해결한 경우 `close #issue-number`

2023-11-05 17:00 UTC, j8won approved these changes
규민님 정말 수고하셨습니다!!! 어이없는 에러 때매 넘 고생하셨어요
이제 걱정이 없다.. 모든 것을 이해한 이규민이 간다.. 앞으로도 화이팅!!

2023-11-10 04:23 UTC, sihyonn requested changes

2023-11-10 04:23 UTC, sihyonn commented on src/src/api/celebrityAPI.js
> +    url: API.CELEBRITY.LIST,
규민님 api문서 보면 /celebs/recommend 여기로 보내야하는데 해당 url은 /celebs로 가는거같아요
celebId를 기반으로 조회하는게 명세에 안보여서 빼셔도 괜찮을것 같은데 한번 확인해보면 좋으실것같아요!

2023-11-10 04:23 UTC, sihyonn commented on src/src/components/celebrity-list/SimpleCelebList.jsx
> +  const { data: simpleCelebListData } = useSimpleCelebInfoQuery();
이건 그냥 const { data } = useSimpleCelebInfoQuery()로 받아오셔서 이제 이 data를 활용하시면 될거같아요!

2023-11-10 04:23 UTC, sihyonn commented on src/src/hooks/api/celebrity/useSimpleCelebInfoQuery.js
> +      return celebrityAPI.getSimpleCelebInfoList({});
이건 return await 그대로 가시면 될거같습니다!

2023-11-10 04:25 UTC, sihyonn commented on src/src/components/celebrity-list/SimpleCelebList.jsx
> +  const { data: simpleCelebListData } = useSimpleCelebInfoQuery();
data가 있다면 SimpleCelebCard를 뿌려주는식으루요

2023-11-10 04:27 UTC, sihyonn commented
그리고 머지하실때!!!!!
메인의 추천셀럽카드가 제가 작업한 마이펀딩 팔로잉목록의 셀럽카드와 동일해서 충돌이 많이날거같아서
요부분 참고해주시면 감사하겠습니당🥹

2023-11-10 04:30 UTC, sihyonn commented on src/src/hooks/api/celebrity/useSimpleCelebInfoQuery.js
> +    [API.CELEBRITY.LIST],
요기가 처음 API 요청 url이 달라서 
예를들어.. API.CELEBRITY.RECOMMEND 요런식으로 constants에 추가하시구 사용하시면 될거같슴듕

2023-11-10 04:35 UTC, j8won commented on src/src/components/celebrity-list/SimpleCelebList.jsx
> +  const { data: simpleCelebListData } = useSimpleCelebInfoQuery();
기존에 저희가 array로 데이터 만들었던 것 대신에 data를 활용해서 컴포넌트에 뿌려주면 돼요!

2023-11-10 15:35 UTC, sihyonn approved these changes

2023-11-10 15:57 UTC, merged