Feat#16 공통컴포넌트 - Form
Step3-kakao-tech-campus/Team13_FE pull request #28
Opened 2023-10-03 15:20 UTC by sihyonn

## 주요 사항
- 라벨 + 입력칸 = LabeledInput.jsx
- 여러개의 LabeledInput = From.jsx
- 주원님이 추천하셔서 로그인페이지에 테스트겸 넣어보았습니다.

## 스크린샷

![FA619EAF-02A4-4D41-AFC6-A3C933F404BF](https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/96de93ae-785f-4d0c-aee0-9c59dcd4a3ff)

![C1F682DB-14FF-4531-92B5-6B5E1E180D23](https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/9528089b-15d8-49dc-a3c1-41bb4261b382)

![F204B916-858F-4ED0-803C-A9259BF138E3](https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/399c4719-7780-442d-9c08-e1d8e4741768)

## 궁금한 점

- 스타일링을 제멋대로 한 거 같아서 확인 후에 앞으로는 어떻게 해야할지 말씀해주시면 바로 새겨듣겠습니다!🥹
- 그 유효성검사에 맞춰서 입력칸 테두리도 빨강색상으로 하려했는데 적용이 안되서 일단 제외시켰는데 이것도 봐주세요!!
- 카카오 로그인 버튼은 아직 api 안가져와서 일단 임의로 넣어둔 것입니다!(나중에 카카오로그인 api로 바꾸겠습니다)
- 많이 부족한데 조언해주시면 수정하겠습니다. 기다려주신 주원님 규민님 감사해요!

### 관련 이슈

2023-10-03 17:07 UTC, j8won commented
- 유효성 검사와 스타일링은 전반적으로 검토하며 코멘트 남기겠습니다
- 카카오 로그인 api는 아직 안 해도 괜찮습니다!! 아마 저희 api 연결도 다 해야 할 수 있지 않을까 싶네요
- 수고하셨습니다! 아직 코드 확인 전이지만 결과물은 좋아보여요 ㅎㅎ

질문
1. 이런 메시지 넣는 것도 구현되어 있는 건가요?
<img width="305" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/75734220/7f68f9a4-9486-49e5-830d-0335a3326b5b">

2023-10-03 17:31 UTC, j8won requested changes
react hook form 처음 사용해서 많이 헷갈리셨을 것 같은데 정말 수고하셨습니닷 !!! ㅎㅎ
작성한 리뷰 읽어보시고 수정할 부분은 수정해주세요.

그리고 (저도 그랬지만 ㅋㅋㅠ) 전체적으로 jsdoc이 누락되어 있습니다
`/**` 입력하고 엔터 입력하면 쉽게 입력할 수 있어요

<img width="573" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/75734220/783a1255-46e3-4192-9692-152bd0296d1d">

다 입력할 필요 없고 이런 식으로 간단히만 입력해도 되니까 작성 부탁드려요~

2023-10-03 17:31 UTC, j8won commented on src/src/pages/LoginPage.jsx
> +      // label: "비밀번호",
주석은 필요하지 않은 게 확실하다면 지우는 게 좋을 것 같아요!

2023-10-03 17:31 UTC, j8won commented on src/src/pages/LoginPage.jsx
> +    },
이런 상수의 경우 `@/constant` 디렉토리에서 관리하면 좋을 것 같습니다!

각각 FORM_DEFALT.js와 FORM_INFO.js로 나눠보는 것은 어떨까요?
`Object.freeze();`를 활용해 객체를 동결시키는 것도 추천합니다

[링크](https://github.com/j8won/step2-FE-kakao-shop-1/blob/main/src/constants/FORM_INFO.js)를 참고해보세욧 ㅎㅎ

2023-10-03 17:31 UTC, j8won commented on src/src/pages/LoginPage.jsx
> +  `,
BottomMsg보다 `SignUpMsg`라는 네이밍이 더 적절할 것 같습니다.
변수를 네이밍할 때 스타일링을 기준으로 해도 괜찮지만, 기능에 대해 의미를 담고 있으면 더 좋아요!

2023-10-03 17:31 UTC, j8won commented on src/src/components/common/form/Form.jsx
> +};
`propTypes`에서 `isRequired`가 아닌 경우에 `defaultTypes`를 정의하는 것이 좋습니다!

2023-10-03 17:31 UTC, j8won commented on src/src/components/common/form/Form.jsx
> +  Form: styled.form``,
따로 스타일링이 들어가지 않는다면 `<Styled.Form>` 대신 `<form>`으로 대체해도 괜찮을 것 같아요!

2023-10-04 03:21 UTC, Klomachenko approved these changes

2023-10-04 03:21 UTC, Klomachenko commented on src/src/components/common/form/Form.jsx
> +};
`propTypes` 어려워보이던데.. 시현님 대단하시네요

2023-10-04 10:51 UTC, j8won approved these changes
수고하셨습니다!

2023-10-05 04:16 UTC, merged