[FE]CelebInfoGridCard 셀럽 페이지 컴포넌트#32
Step3-kakao-tech-campus/Team13_FE pull request #39
Opened 2023-10-05 19:15 UTC by Klomachenko

## 주요 사항
- CelebInfoGridCard 생성
- 손흥민 혹은 타 셀럽 사진의 경우 동그랗게 가공을 하게 되는데, 그 경우는 어떻게 해야할 지 정확히 모르기 때문에, 아이콘으로 대체함
- esLint와 prettier 간에 충돌이 발생하였음
  - `prettierc.js` 파일을 루트디렉토리에 생성하여 해결함

## 스크린샷
<img width="395" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/102893954/e49f77f1-1492-4f8d-95e2-b8d30d64aec6">

## 궁금한 점
- styled Component로 디자인을 수정하였습니다
  - 최대한 주원님과 변수명을 비슷하게 하려 하였는데 알맞게 되었는지
  - 수정할 부분이 있거나 나쁜 습관이 보인다면 어떻게 고치면 좋을지
- 팔로우 버튼의 경우 새로 컴포넌트를 생성하라고 하셨는데, 있는 버튼을 사용해보라고도 하셔서 우선 있는 버튼을 사용하여 바꾸었습니다
- money, In progress, user 아이콘의 경우에는 크기를 몇으로 하면 좋을지
- `prettierc.js` 파일은 저만 생성하였는데, 이것을 merge 후에 pull 받으면 시현님 로컬에서 에러가 발생하지 않을지 우려됨

### 관련 이슈
close #32

2023-10-06 04:43 UTC, sihyonn approved these changes
음 문제가있을까싶은데 풀해보고 충돌여부를 확인해봐야겠네요?

2023-10-06 05:06 UTC, j8won requested changes
여러모로 prettier 설정도 해결하느라 수고하셨습니다! 코멘트 남긴 부분 확인하고 변경해주세요~ 디자인을 세세하게 px 단위까지 꼭 따를 필요는 없지만 그래도 어느 정도 따라가고 크기 정도만 조절해야 합니다. 코드 작성하며 PC에서의 뷰, 모바일에서의 뷰, 피그마 디자인 번갈아가며 확인해주세요!

+ CelebInfoGridCard의 경우 1, 2, 3등은 다음과 같이 뱃지가 붙습니다
<img width="780" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/75734220/49c9b01e-e541-4425-9ab3-76a36089bed8">

1. 아이콘에 `memo` 적용하지 말기
2. 아이콘은 {아이콘명}Icon.jsx로 @/assets/icon에 저장하기
3. 아이콘에 색상 부여하기
4. 아이콘 디자인대로 크기 줄이기 16*16
5. 작은 아이콘과 텍스트 사이가 조금 더 넓어야 함 => 어떻게 스타일링 할지 고민해보기

2023-10-06 05:06 UTC, j8won commented on src/src/components/common/CelebInfoGridCard.jsx
> +function CelebInfoGridCard() {
props로 `celebId`, `celebName`, `fundInProgressNum`, `totalFundMoney`, `followerNum`을 받아서 활용해 보세요.

2023-10-06 05:06 UTC, j8won commented on src/src/components/common/CelebInfoGridCard.jsx
> +    justify-content: space-around;
hover 스타일링을 적용해보세요! [참고](https://github.com/Step3-kakao-tech-campus/Team13_FE/blob/develop/src/src/components/common/fund/FundInfoGridCard.jsx)

```css
&:hover {
  transform: ${({ theme }) => theme.transform.gridCard};
  box-shadow: ${({ theme }) => theme.boxShadow.gridCard};
  transition: ${({ theme }) => theme.transition.gridCard};
}
```

2023-10-06 05:08 UTC, j8won commented on src/src/components/common/CelebInfoGridCard.jsx
> +            </Button>
팔로우 버튼의 경우 공통 컴포넌트인 Button을 활용하며 따로 컴포넌트로 생성해 보라는 소리였어요! 추후 api 통신이 추가되면 팔로우 버튼은 모두 동일한 요청을 보내게 될 것이니, 기능을 미리 분리해주는 셈입니다.

2023-10-07 05:14 UTC, Klomachenko commented
> 음 문제가있을까싶은데 풀해보고 충돌여부를 확인해봐야겠네요?

확인 한 번 부탁드릴게요!

2023-10-07 05:17 UTC, Klomachenko commented on src/src/assets/SignUpIcon.jsx
>    );
`singleQuote: false` 적용 완료했습니다!

2023-10-07 05:27 UTC, Klomachenko commented on src/src/assets/celebinfo-card/Celeb.jsx
> +import { memo } from 'react';
전부 다 memo 삭제 완료했습니다! memo를 그냥 넣었었는데, 어디에 쓰는지도 공부 해볼게요!

2023-10-07 05:37 UTC, Klomachenko commented on src/src/components/common/CelebInfoGridCard.jsx
> +          <Styled.Text main className="name">
main은 '손흥민' 이라는 글자를 1.25rem으로 키우고 나머지는 main 이 아닐시엔 그냥 기본 글자인 0.5rem을 유지할 수 있게 해놓았습니다.

해당 코드입니다.

`font-size: ${({ main }) => (main ? "1.25rem" : "0.5rem")}`

2023-10-07 05:42 UTC, Klomachenko commented on src/src/components/common/CelebInfoGridCard.jsx
> +        <Celeb />
해당 아이콘이라고 함은 User 아이콘을 말씀하시는건가요?

2023-10-07 05:48 UTC, Klomachenko commented on src/src/components/common/CelebInfoGridCard.jsx
> +            </Button>
스타일링은 수정하였고 issue 생성해서 추가로 팔로우 버튼 컴포넌트를 생성할까요?

2023-10-07 05:49 UTC, j8won commented on src/src/assets/celebinfo-card/Celeb.jsx
> +import { memo } from 'react';
memo랑 같이 useCallback, useMemo도 공부하면 좋을 것 같아요! 저도 가물가물하니 같이해요~

2023-10-07 05:51 UTC, j8won commented on src/src/components/common/CelebInfoGridCard.jsx
> +        <Celeb />
`Celeb.jsx`를 말한 거였어요! 프로필 사진이 없는 경우에는 피그마와 같이 test-account 아이콘을 사용하면 됩니다 참고로 프로젝트 내 아이콘명은 모두 피그마의 아이콘명과 같습니다.

2023-10-07 05:53 UTC, j8won commented on src/src/components/common/CelebInfoGridCard.jsx
> +          <Styled.Text main className="name">
아하!! 좋습니다! 혹시 브라우저 콘솔에서 main 네이밍과 관련해 에러가 나타나진 않았나요? 종종 정상 작동함에도 스타일드 컴포넌트 props 콘솔 오류가 생기는데, 그럴 때는 `$main`과 같은 식으로 앞에 `$`를 붙여주면 되니 참고하세요~

2023-10-07 05:53 UTC, j8won commented on src/src/components/common/CelebInfoGridCard.jsx
> +            </Button>
기존 이슈 To do에만 할 일로 추가하고 진행해도 괜찮습니당

2023-10-07 05:59 UTC, j8won commented
> > 음 문제가있을까싶은데 풀해보고 충돌여부를 확인해봐야겠네요?
> 
> 
> 
> 확인 한 번 부탁드릴게요! 

규민님 이건 이 pr이 머지한 후에 확인 가능해서 아마 시현님이 추후에 확인가능하실 것 같아요

2023-10-08 00:11 UTC, j8won commented on src/src/assets/celebinfo-card/Celeb.jsx
> +export default InProgress;
해당 파일은 삭제 부탁드려요~

2023-10-08 00:13 UTC, j8won commented on src/src/components/common/CelebInfoGridCard.jsx
> +        <Celeb />
@Klomachenko 이 부분 다시 체크 바랍니다! [예시](https://github.com/Step3-kakao-tech-campus/Team13_FE/pull/40/files)
<img width="868" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/75734220/333df593-38c5-4a8a-8be6-02d22e31a89c">

2023-10-08 00:15 UTC, j8won approved these changes
수고하셨습니다! src/src/assets/celebinfo-card/Celeb.jsx랑 src/src/components/common/CelebInfoGridCard.jsx만 다시 확인해 주세요!

2023-10-08 05:49 UTC, Klomachenko commented on src/src/components/common/CelebInfoGridCard.jsx
> +            </Button>
넵 알겠습니다!

2023-10-09 09:32 UTC, j8won approved these changes
아주 좋습니다!! 정말 수고하셨어요
팔로우(팔로잉) 버튼 컴포넌트화 하고 충돌 해결 후 머지해주세요!

2023-10-09 18:28 UTC, merged