회원가입페이지(미완성 부분 존재)
Step3-kakao-tech-campus/Team13_FE pull request #51
Opened 2023-10-09 09:02 UTC by sihyonn

## 주요 사항
- 회원가입페이지 생성 및 FORM_INFO, FORM_DEFAULT 업데이트
- 아직 미완성부분👇🏻
- 이메일 폼 입력칸 중복확인 버튼 사이즈 조절
- 비밀번호 일치여부 확인

## 스크린샷
![C44992D8-FC9F-40C7-A762-A7EB4CFA421C](https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/17012cac-6e73-4b71-a564-49fcabd3e328)

![B9385AE2-CFDA-4800-8268-3195C22C2E15_4_5005_c](https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/38b720f6-3a0e-4618-bfbe-ddec46292ef0)

## 궁금한 점
- 이메일 폼 인라인스타일로 줄어들지 않아요.. 중복확인버튼과 이부분을 어떻게 해결하면 좋을까요?\
- 비밀번호 일치여부 : 문서찾아보면서 하는데 FORM_INFO로 따로빼서 하는 예시가 없어서 조금..어렵습니다. 제가 작성해놓은 코드는 아닌거같아서요😢
- 추가적으로 공통구현된 체크박스를 썼는데 잘 안보이는 것 같아서 스타일링 뭐 더 추가해야할까요?

완벽히 해서 내고 싶었는데 빨리 공유하고 수정해야할 것 들과 조언을 듣고자 미완성이지만 일단 제출하고
수정 빠르게 해보고자 pr보내요!! 한번 확인해주시면 감사하겠습니다.

### 관련 이슈
이슈를 해결한 경우 `close #issue-number`

2023-10-09 09:30 UTC, j8won requested changes
시현님!! 먼저 고생하셨습니다! 질문을 보니 오랜 고민이 느껴집니다.. 부족하지만 리뷰 남겨요 ㅎㅎ

> 1. 이메일 폼 인라인스타일로 줄어들지 않아요.. 중복확인버튼과 이부분을 어떻게 해결하면 좋을까요?
- 이건 기존 디자인을 완벽하게 따르려면 LabeledInput Form 공통 컴포넌트 활용을 포기해야 합니다
- 그런데 공통 컴포넌트 포기하기... 아쉽잖아요? 일단 있는 걸 잘 활용하는 게 리소스 아끼는 거기도 하고?
- 그래서 제 생각에는 아예 중복확인 버튼을 없애는 건 어떨까요?

```js
{
    id: "userId",
    label: "아이디",
    type: "text",
    validation: {
      required: "아이디를 입력해 주세요",
      validate: {
        checkUrl: async (value) => {
          if (value.length <= 2) {
            return;
          }
          try {
            await UserAPI.checkIsIdDuplicated(value);
          } catch (e) {
            return (
              e.response.data === "아이디가 중복되었습니다." &&
              "중복된 아이디입니다."
            );
          }
        },
      },
    },
  },
```
- 위와 같이 [콜백 함수](https://react-hook-form.com/docs/useform/register)를 validate로 줄 수 있습니다
- 아예 중복 확인 버튼을 없애고 이를 이용해 이메일 중복 여부를 확인하는 것을 추천드려요

> 비밀번호 일치여부 : 문서찾아보면서 하는데 FORM_INFO로 따로빼서 하는 예시가 없어서 조금..어렵습니다. 제가 작성해놓은 코드는 아닌거같아서요😢
- 방법은 따로 있긴 한데...
- 비밀번호 일치 여부 사실 아예 제거해도 괜찮을 것 같아요
- 요즘에는 비밀번호 두 번씩 입력하는 거 UI/UX에서 별로라고 없애는 추세라고 들었어요
- 디자인 할 때 일단 화면 채운다고 넣었는데 그냥 아예 빼도 괜찮을 것 같습니다 ㅋㅋㅋ 어차피.. api 통신할 때 필요 없기도 하고요

> 추가적으로 공통구현된 체크박스를 썼는데 잘 안보이는 것 같아서 스타일링 뭐 더 추가해야할까요?
- 저거는 어차피 이 화면 뿐만 아니라 공통적으로 안 보이는 부분 같네요?! 저의 실수.. ㅎㅎ;;
- border의 색상을 조금 더 진한 색상으로 시현님께서 골라서 바꿔 주세요!

2023-10-09 17:23 UTC, Klomachenko approved these changes

2023-10-10 04:37 UTC, sihyonn commented
![image](https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/d6c46e21-8288-4925-a6f7-502adbc14b95)
<img width="499" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/22715b0d-6dd2-493a-a5e1-7f0b162ce41e">

이메일 중복검사는 임의로 만들어서 테스트했습니다! 중복여부 50:50으로 해서 중복이면 메시지뜨게 했는데 한번봐주시면 감사하겠습니다.
api 연동하면 수정하겠습니다!

2023-10-10 06:05 UTC, j8won approved these changes
수고하셨습니다! 버튼과 동의 체크박스 위치만 옮기고 머지해도 될 것 같아요

2023-10-10 06:05 UTC, j8won commented on src/src/constants/FORM_INFO.js
> +            }
Promise 활용하는 거 너무 좋은 아이디어 같아요!

2023-10-10 06:05 UTC, j8won commented on src/src/pages/SignUp.page.jsx
> +      </Button>
전송 버튼을 `<Form></Form>` 안에 위치해야 onSubmit 이벤트가 기대한대로 작동합니다!!

``` jsx
<Form>
  <SignUpAgree>
  ...
</SignUpAgree>
  <Button>회원가입</Button>
</Form>
```

2023-10-10 08:45 UTC, sihyonn commented on src/src/pages/SignUp.page.jsx
> +      </Button>
엇 감사합니다!

2023-10-10 08:51 UTC, merged