FollowButton 컴포넌트화
Step3-kakao-tech-campus/Team13_FE pull request #55
Opened 2023-10-10 14:11 UTC by Klomachenko

## 주요 사항
- FollowButton 컴포넌트 생성
- 팔로우가 안되어있는경우 -> 팔로우 + 빨간색 + hover 적용 O
- 팔로우가 되어있는 경우 -> 팔로잉 + 하얀색 + hover 적용 X
- 추가한 props
` * @param {boolean} isFollowing 팔로잉 여부`
` * @param {number} celebId 셀럽 아이디`

## 스크린샷
<img width="188" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/102893954/6e915681-8e43-42c8-a3b5-53395d637987">

## 궁금한 점
- celebId 의 경우 임의로 1, 2로 지정해놓은 상태입니다. 
- 잘 적용한건지 정확하진 않지만 공통 버튼 컴포넌트를 가져와 프롭스의 자료형 또한 지정해 주었는데 잘 된건지 확인 부탁드리겠습니다.
- 아래처럼 자동으로 지정해주고 싶은데 if 혹은 삼항연산자를 사용하면 더 좋을까요?
  - `isFollowing={true}` 인 경우엔 `isHoverStyle={false}`, `styleType={BUTTON_TYPE.PRIMARY}`
  - `isFollowing={false}` 인 경우엔 `isHoverStyle={true}`, `styleType={BUTTON_TYPE.SECONDARY}`

### 관련 이슈
이슈를 해결한 경우 `close #issue-number`

2023-10-10 14:14 UTC, j8won commented on src/src/components/common/button/FollowButton.jsx
> +    }
스타일링의 경우 따로 할 필요없이 `@/component/common/Button.jsx`를 이용하고 로직만 작성하는 건 어떨까요?

2023-10-10 14:20 UTC, j8won requested changes
스타일링이 기존의 common/Button.jsx와 겹치기 때문에 그것을 이용하면 좋을 것 같아요! 그러면 추가적으로 매개변수로 children, styleType, isHoverStyle도 안 받아도 되고요~

팔로우 버튼과 팔로잉 버튼에 대해 handle이벤트 함수를 만들어서 미리 간단히 팔로우 신청, 팔로잉 취소 로직을 분리해 봅시다! (console.log로만 확인해도 좋아요!)

```jsx
if (isFollow) return <Button styleType={BUTTON_TYPE.SECONDARY} style={추가적인 스타일링} {...props}>팔로우</Button>
<Button styleType={BUTTON_TYPE.PRIMARY} style={추가적인 스타일링} {...props}>팔로잉</Button>
```

2023-10-12 15:52 UTC, Klomachenko commented on src/src/components/common/button/FollowButton.jsx
> +    }
음 우선 최대한 가져와서 쓰려고 했는데 import 해서 가져와서 쓰라는 말씀이신거죠? 저는 그냥 코드를 그대로 복붙해와버린 느낌이라서
 
'로직'은 뭘 뜻하는건가요? props 로 받아오는 `isHoverStyle`, `styleType`을 말씀하시는 건가요?

2023-10-12 16:08 UTC, Klomachenko commented on src/src/components/common/button/FollowButton.jsx
> +    }
아 아래 글 보고 로직에 대해 이해하였습니다.

팔로우 상태인 버튼을 클릭할 시에, 팔로우가 안 된 상태인 버튼을 클릭할 시에 각 다른 문구가 console에 출력되도록 일단 구현하도록 하였습니다.

2023-10-12 16:09 UTC, Klomachenko commented
## 결과
<img width="1840" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/102893954/13c14be9-3888-46d9-92fd-4d1160834c53">

## 로직 분리 및 콘솔창 출력 코드 
```jsx
const handleFollowClick = () => {
    // 팔로우 버튼 클릭 시 로직
    console.log('셀럽을 팔로우합니다!')
  }
  const handleUnFollowClick = () => {
    // 팔로우 버튼 클릭 시 로직
    console.log('셀럽을 언팔합니다!')
  }
```

2023-10-13 05:41 UTC, j8won commented on src/src/components/common/button/FollowButton.jsx
> +function FollowButton({ children, styleType, isHoverStyle, celebId, isFollowing, ...props }) {
`isHoverStyle=false`로 미리 default 값을 주면 컴포넌트 사용할 때 편할 것 같아요! 그리고 `styleType`은 매개변수로 받을 필요가 없어보입니다!

2023-10-13 05:44 UTC, j8won approved these changes
수고하셨습니다! 리뷰 확인해주시고 추가적으로 PropTypes가 빠진 것 같으니 해당 부분 추가한 다음 머지해주세요!

2023-10-13 05:44 UTC, j8won commented on src/src/components/common/button/FollowButton.jsx
> + */
코드리뷰에서 받은 피드백처럼 children은 {`React.ReactNode}` 사용해주세요! 그리고 셀럽 아이디는 아직 타입이 확실하지 않기 때문에 `{string | number}`가 좋을 것 같습니다 props는 `htmlButtonProps`으로 매개변수명을 바꾸고 `{html.Attributes}`로 해주세요!

2023-10-13 06:11 UTC, merged