셀럽신청 모달
Step3-kakao-tech-campus/Team13_FE pull request #79
Opened 2023-10-19 07:29 UTC by sihyonn

## 주요 사항
- apply-celebrity폴더 생성하여 CelebApplyModal, SelectForm 작성
- 일반 입력(이름, 소속그룹)은 CelebApplyModal에서 그대로 작성
- 선택형(성별, 분류)는 SelectForm 따로 분리해서 작성
- 성별, 분류 옵션 constants에 따로 작성
- 토스트 에러 처리
  - 해결 : 셀럽이미지, 이름
  - 미해결 : 성별, 분류
  - 필요없음 : 소속그룹(선택사항이라 처리하지않았습니다)
  

## 스크린샷
<img width="1036" alt="스크린샷 2023-10-19 오후 4 16 16" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/ad51d7bc-1523-4256-8ae3-1d9d57ff4ca1">

<img width="406" alt="스크린샷 2023-10-19 오후 4 17 06" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/5b2acf93-20b1-4b3e-bfb5-8c110b7afd5e">

## 궁금한 점
셀렉트 폼에 그냥 성별, 분류 두가지를 같이 작성하려다가
나중에 또 사용할 수도 있을 것 같아서 재사용이가능할지 모르겠지만 따로 사용 가능하게 작성을 하게되었는데요. 그러다보니 에러처리를 할때 얘네의 상태를 어떻게 따로 에러시 해당 옵션에대한 메시지를 처리하게 해줘야 할지를 아직 모르겠습니다...🥲
먼저 상황 공유하고자 pr 보냅니다! 리뷰주시면 이 사항과 나머지 추가적으로 리팩토링 필요한 부분 수정해보도록 하겠습니다.

### 관련 이슈
close #67

2023-10-19 07:51 UTC, j8won requested changes
수고하셨습니다! 코멘트가 도움이 되길 바랍니다 ㅎㅎ

- `성별`, `분류`의 `선택하세요와` `arrow` 아이콘의 색이 `비활성` 색깔이면 좋을 것 같습니다! 선택이 안 된 상태와 선택이 된 상태를 구분해 보아요. 아니면 미리 하나를 선택한 상태여도 좋을 것 같습니다
- SelectForm보다는 SelectInput이 컴포넌트명에 더 잘 어울릴 것 같아요! 그리고 아직 재사용 여부는 모르겠지만 공통 컴포넌트에 더 잘 어울리는 것 같습니다!
- @/components/apply-celebrity의 디렉토리명을 celebrity-list로 바꾸는 건 어떨까요? 셀럽 신청이 페이지가 아닌 셀럽 목록 페이지의 모달창이니까요!

2023-10-19 07:51 UTC, j8won commented on src/src/components/apply-celebrity/CelebApplyModal.jsx
> +import ThumbnailBox from "../create-fund/ThumbnailBox.jsx";
ThumbnailBox를 앞으로 계속 사용하게 될 것 같은데, 해당 컴포넌트를 사이즈 조절이 가능하게 매개변수를 추가하고 공통 컴포넌트로 바꾸는 것은 어떨까요?

2023-10-19 07:51 UTC, j8won commented on src/src/components/apply-celebrity/CelebApplyModal.jsx
> +        ></Styled.Input>
input 태그를 닫는 것으로 바꿔주세요!

2023-10-19 07:51 UTC, j8won commented on src/src/components/apply-celebrity/CelebApplyModal.jsx
> +  };
이름, 성별, 분류를 하나의 Object로 관리하면 좋을 것 같습니다!
useState로 관리해도 좋고, useRef로 관리해도 좋아요! (이 부분은 제어/비제어 컴포넌트에 관해 찾아보는 것을 추천합니다)
```js
const [textCelebInfo, setTextCelebInfo] = useState({ name: "", gender: "", category: ""});
```

위와 같은 식으로 하나의 상태로 관리를 하고 `handleGenderChange`, `handleCatergoryChange`에서 setState을 통해 선택된 정보를 관리해보세요!

2023-10-19 07:51 UTC, j8won commented on src/src/components/apply-celebrity/CelebApplyModal.jsx
> +      }}
<img width="696" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/75734220/7c8ef63f-f34f-4bfb-a5ee-5817ade32d7e">

이렇게 하면 위와 같이 모바일에서 꽉찬 화면이 구현이 되지 않지 않나요?! 만약 PC일 때 특정한 너비를 주고 싶은 거면 min-width를 사용하는 거 어떨까요? 그리고 height은 아예 사용하지 않고 내부 컴포넌트에 padding값을 주는 것을 활용해 높이를 조절하면 좋을 것 같습니다.

2023-10-19 07:51 UTC, j8won commented on src/src/components/apply-celebrity/CelebApplyModal.jsx
> +      <></>
오타는 제거해주세요!

2023-10-19 07:51 UTC, j8won commented on src/src/constants/SELECTFORM_INFO.js
> +];
value 값을 대문자로 바꿔주세요!

2023-10-20 04:26 UTC, sihyonn commented on src/src/components/apply-celebrity/CelebApplyModal.jsx
> +import ThumbnailBox from "../create-fund/ThumbnailBox.jsx";
한번 수정해보도록하겠습니다!

2023-10-20 04:27 UTC, sihyonn commented on src/src/components/apply-celebrity/CelebApplyModal.jsx
> +      }}
오오오!!! 감사합니다 반영해서 수정하겠습니다!

2023-10-21 08:55 UTC, j8won requested changes
수고하셨습니다! 

모달창 내 상태의 경우 api를 요청할 때 필요하기 때문에 `CelebApplyModal.jsx`에서 선언되어야 나중에 추가적인 코드 변경 없이 진행할 수 있습니다.

`ThumnailBox.jsx`의 경우 css를 변경하면서 확인해봐야 정확히 알 것 같아서... 해당 부분은 나중에 지금 PR 머지되면 제가 한번 봐보겠습니다 머지할 때 한번 저에게 리마인드 해주세요!

2023-10-21 08:55 UTC, j8won commented on src/src/components/celebrity-list/CelebApplyModal.jsx
> +    });
```javascript
setTextCelebInfo((prev) => {...prev, [fieldName]: value,});
```
로 변경하는 건 어떨까요

2023-10-21 08:55 UTC, j8won commented on src/src/components/celebrity-list/SelectInput.jsx
> +  const [selectedOption, setSelectedOption] = useState("");
해당 상태를 SelectInput 말고 CelebApplyModal에서 관리해야 나중에 api 통신할 때 전달이 가능합니다!

2023-10-21 08:55 UTC, j8won commented on src/src/components/celebrity-list/SelectInput.jsx
> +      >
텍스트 색상의 경우 value가 `null`일 때 다르게 해주면 되지 않을까요?!

2023-10-22 07:56 UTC, sihyonn commented
@j8won 님 수정해봤는데 확인 한번만 부탁드립니다!
그리고 텍스트 색상변경은.... 다양하게 시도해봤는데 아직도 적용이 안되는데 뭐가문제일까요ㅠㅠ
추가적으로 jsdoc과 propTypes도 바로 명시하도록 하겠습니다.

2023-10-22 18:34 UTC, j8won approved these changes
색깔 변경은 아마 리뷰처럼 하면 될 것 같은데 안 되면 머지 후에 제가 한번 봐보겠습니다!! 수고하셨습니다 👍

2023-10-22 18:34 UTC, j8won commented on src/src/components/celebrity-list/SelectInput.jsx
> +      selectedValue === "" ? "#aaaaaa" : "#000000"};
`selectedValue` 말고 `value`로 변경해보세요!

2023-10-26 04:24 UTC, merged