셀럽상세페이지
Step3-kakao-tech-campus/Team13_FE pull request #89
Opened 2023-10-28 09:35 UTC by sihyonn

## 주요 사항
- 셀럽상세페이지
- 셀럽정보와, 셀럽관련펀딩정보로 나눠서 작업
- 팔로워, 펀딩금액 순위가 1~3에 들지 않는 경우 텍스트로 등수 표시
- 미해결 이슈
1️⃣ 셀럽정보(윗부분)부분이 모바일 사이즈에 맞춰지지 않았다는점
2️⃣ 아이콘과 텍스트 등수가 같이 존재할때 둘 비율이 잘 맞지 않는 점 ex) 1등 4등 
3️⃣ 텍스트정보에 아이콘 크기조절

## 스크린샷
<img width="1198" alt="스크린샷 2023-10-28 오후 6 23 32" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/9dc6e22c-6bca-40de-9a5e-4c4498e66f3c">

<img width="1146" alt="스크린샷 2023-10-28 오후 6 24 08" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/b7efba8c-a352-47d4-a645-51658d1f256d">

## 궁금한 점
아직 데이터 가져오는 부분을 생각하지 않아서 일단 임시로  info로 다 넣어버리고 작업했는데 이부분은 추후에 수정하도록하겠습니다!
이부분에 대해서 리뷰해주실 점 있으시면 말씀해주세요!
창 줄이면 자동으로 조절이 되어야하는데 상단부분이 안되는거 같습니다. 무엇이 문제일까요?
미해결 이슈에 관해서 잘 봐주시면 감사하겠습니다.😃(전체적으로 스타일 적용된 부분도요!)

### 관련 이슈
close #76

2023-10-29 07:06 UTC, j8won requested changes
시현님 너무 수고하셨습니다! 현재 코드에서 크게 바꿀 부분은 없을 것 같고, 질문하신 부분 보완이 되면 좋을 것 같습니다.

 1. 셀럽정보(윗부분)부분이 모바일 사이즈에 맞춰지지 않았다는점
현재 pc에서는 아래와 같습니다
<img width="571" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/75734220/bbdd2698-cc4c-4d2b-bf49-4ff2e33cb35b">

컴포넌트를 CelebProfile, CelebRank, CelebTextInfo로 잘 나누어주셨는데요. 해당 컴포넌트들을 div로 가싸고 특정 사이즈 (컴포넌트가 깨지기 시작하는 사이즈) 미만일 때  flex-direction: column으로 변경하면서 flex의 방향을 바꾸는 것을 추천드려요! 그리고 팔로우 버튼은 따로 position absolute를 활용하면 적절하게 위치할 수 있을 것 같습니다

2️⃣ 아이콘과 텍스트 등수가 같이 존재할때 둘 비율이 잘 맞지 않는 점 ex) 1등 4등

이거는 아이콘의 사이즈를 조절하면 해결되지 않을까요?
<img width="634" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/75734220/6a5db0be-f1e4-4f30-918d-5e9350c2c799">

이런 식으로 기존 값을 default로 둬서 기존에 사용된 아이콘에 영향을 안 가게 처리하게 따로 사이즈를 주면 될 것 같아요

3️⃣ 텍스트정보에 아이콘 크기조절
위와 마찬가지입니다

2023-10-29 12:26 UTC, sihyonn commented on src/src/components/celebrity-detail/CelebProfile.jsx
> +        {affiliation && <span>{affiliation}</span>}
@j8won  오 감사합니다 사실 afiiliation 해야할지 group해야할지 from해야할지 고민이 많았거등요..🥹
주원님 주신 리뷰 참고해서 수정해서 돌아올게요!!!

2023-10-29 16:10 UTC, sihyonn commented
리뷰 요청하신대로 스타일 변경하였습니다!
+ 아이콘들 사이즈 조절 가능하도록 변경
+ 순위아이콘과 뱃지가 함께 있는 경우 위치 조절
+ 화면 너비 줄어들때 세로로 정렬

팔로우 버튼을 아래쪽으로 위치시키는게 괜찮을거 같아서 일단 그렇게 했는데 괜찮을까요?
@j8won  @Klomachenko  확인 한번 부탁드립니다🔥

<img width="1092" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/2766293d-42af-461c-8599-3c22c7e07297">

<img width="477" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/c2a4f3fa-5ba7-4ffe-b3d2-57f833fa2a54">

2023-10-30 05:57 UTC, j8won approved these changes
@sihyonn 모바일 화면에서 padding이 너무 큰 것 같아요... 미디어 쿼리를 활용해 패딩 값을 0으로 변경해보세요!!  🥹 팔로잉 버튼 위치는 좋습니다~

2023-10-30 06:23 UTC, Klomachenko approved these changes

2023-10-30 13:43 UTC, merged